apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
images:
- name: quay.io/openshift/origin-vertical-pod-autoscaler-operator
  newName: quay.io/openshift/origin-vertical-pod-autoscaler-operator
  newTag: 4.17.0
