apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vpa-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vpa-leader-election-role
subjects:
- kind: ServiceAccount
  name: vertical-pod-autoscaler-operator
  namespace: openshift-vertical-pod-autoscaler
